### ISSUE TITLE
Downloads linking is not working correctly

### ISSUE THREAD

**Issue by garthglaum** [lightspeeddevelopment/lsx-health-plan#12]
Linked downloads sometimes do not appear in the backend of meal plan.

When downloads are unlinked from meal plan they will still display on the frontend and / or the backend.

Deleted downloads show as an error on the frontend (see screenshot)

![image](https://user-images.githubusercontent.com/31071701/66400513-e62af880-e9e1-11e9-9eb1-d6b018358ca7.png)

![image](https://user-images.githubusercontent.com/31071701/66400445-c693d000-e9e1-11e9-896a-6b5c1be4dab6.png)

**Comment by krugazul** [comment]
@garthglaum the reason that "Download not found" link was showing, was because the download was deleted, but the ID for it was still save on the workout.

I have added in a function to filter out any downloads that dont exist.  It is currently working on the [demo](https://lsx-health-plan.lsdev.biz/plan/day-1/) site.
![Downloads Box](https://user-images.githubusercontent.com/1805603/67676312-dde32f00-f989-11e9-8a27-10462564257a.png)

**Comment by krugazul** [comment]
@garthglaum reviewed this via the bugherd bug.  This is only a patch for a larger issue on #20
