### ISSUE TITLE
Add Workout Group Extra Information to Workout Tables

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#58]
**Feature request:**
Add Workout Group Extra Information to Workout Tables

**Description:**
We should add the option for extra information in the Excercise Groups for each Workout

**Solution:**
- [x] Add new Custom Meta Box for Workout Group Information
For each workout group we need a:
- [x] Description - Text Area
- [x] Equipment - Text Input
- [x] Muscle Group - Text Input
- [ ] Call these to front-end

**Testing:**
- [ ]  If no text is entered, then the workout group section should not show.
- [ ]  If there is text entered then it should show, and the text should be formatted.
- [ ]  Is the information showing in the correct place.

**Comment by jacquesvdhorst** [comment]
@krugazul I've pushed the changes for this. I might just need help to not display the extra info if the fields are empty.

**Comment by krugazul** [comment]
@jacquesvdhorst  Im not sure why you added another repeatable section,  each row needs a field so you can insert info.   Have a look at this [commit](https://github.com/lightspeeddevelopment/lsx-health-plan/commit/0f94df9cb4fc7bd2d1877b00eb3c08f6c10bc4a9)  I have moved the fields around.

![Screenshot 2020-01-29 at 14 53 22](https://user-images.githubusercontent.com/1805603/73358365-22db7200-42a7-11ea-8e19-4af427240b2a.png)

w.r.t  because the fields have changed, you will need to removed the stuff you added to `tab-content-workout.php`.     This is how the "[Name](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/tab-content-workout.php#L121)" of the exercise is grabbed.  You just need to do that same as that.

**Comment by jacquesvdhorst** [comment]
@krugazul I've made the changes requested. Can you please re-review. I think we might also just need to introduce the option of the fields not showing when nothing is present. I tried implementing this but failed if you can give me short run-down of what needs to be done I'll implement that.
